use std::io::Error;

pub fn init() -> Result<(), Error> {
    Ok(())
}
